/**
 * Validates that all documentation .md files are linked in the VitePress sidebar config.
 * Also checks for sidebar links that point to non-existent files.
 *
 * Usage: npx tsx scripts/docs/check-wiring.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const projectRoot = path.resolve(import.meta.dirname, '../..');
const docsDir = path.join(projectRoot, 'docs');
const configPath = path.join(docsDir, '.vitepress/config.ts');

// Directories excluded from VitePress build (srcExclude in config.ts)
const excludedDirs = ['node_modules', '.vitepress', 'api', '_templates', 'generated', 'review', 'scripts', 'public', 'assets'];
// Files that are intentionally not in the sidebar
const ignoredFiles = ['/ATTRIBUTION', '/style-guide'];

// 1. Extract all sidebar links from config.ts
const configContent = fs.readFileSync(configPath, 'utf-8');
const linkRegex = /link:\s*['"]([^'"]+)['"]/g;
const sidebarLinks = new Set<string>();
let match;
while ((match = linkRegex.exec(configContent)) !== null) {
  sidebarLinks.add(match[1]!);
}

// 2. Find all .md files under docs/
function findMdFiles(dir: string, base: string): string[] {
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (excludedDirs.includes(entry.name)) continue;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...findMdFiles(fullPath, base));
    } else if (entry.name.endsWith('.md')) {
      let link = '/' + path.relative(base, fullPath).replace(/\.md$/, '');
      if (link.endsWith('/index')) link = link.replace(/\/index$/, '/');
      results.push(link);
    }
  }
  return results;
}

const fileLinks = findMdFiles(docsDir, docsDir).filter(l => !ignoredFiles.includes(l));

// 3. Cross-check
const unwired = fileLinks.filter(l => !sidebarLinks.has(l));
const deadLinks = [...sidebarLinks].filter(l => {
  if (l.startsWith('http')) return false;
  // /api/ is generated by TypeDoc at build time
  if (l === '/api/') return false;
  return !fileLinks.includes(l) && !fileLinks.includes(l + '/');
});

// 4. Report
let exitCode = 0;

if (unwired.length > 0) {
  console.error(`\n❌ ${unwired.length} doc file(s) NOT in sidebar:`);
  unwired.forEach(f => console.error(`   ${f}`));
  exitCode = 1;
} else {
  console.log(`✅ All ${fileLinks.length} doc files are wired into the sidebar.`);
}

if (deadLinks.length > 0) {
  console.error(`\n❌ ${deadLinks.length} sidebar link(s) point to missing files:`);
  deadLinks.forEach(f => console.error(`   ${f}`));
  exitCode = 1;
} else {
  console.log(`✅ All ${sidebarLinks.size} sidebar links resolve to existing files.`);
}

console.log(`\nTotal: ${fileLinks.length} files, ${sidebarLinks.size} sidebar links`);
process.exit(exitCode);
